name: Fix Code Style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: bcmath, dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Run Pint (test mode)
        uses: aglipanci/laravel-pint-action@2.6
        with:
          preset: laravel
